name: Smart Runner CI/CD Pipeline               #just the name of pipeline

on: [push, pull_request]       #when to trigger

jobs: 
    #frontend build jobs
    client-build:          # this is job id not a keyword not necessary only if multiple jobs
     
    runs-on: ubuntu-latest

    defaults: 
    run:
    working-directory: ./client


    steps:
    -name: Checkout code
    -uses: actions/checkout@v3

    -name: Setup Node.js
    -uses: actions/setup-node@v3
    with: 
    node-version: '18'

    -name: Install Dependencies
    run: npm install

    -name: Build client
    run: npm run build


#backend build
server-build:
runs-on: ubuntu-latest
defaults:
run:
working-directory: ./server
steps:
-uses: actions/checkout@v3
-uses: actions/setup-node@v3
with:
node-version: '18'
run: npm install
run: npm test